# Generated by Django 3.2.8 on 2021-10-14 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('cedula', models.BigIntegerField(verbose_name='Cedula')),
                ('nombres', models.CharField(max_length=30, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('telefono', models.BigIntegerField(verbose_name='Telefono')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo_Entidad')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=30, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('experiencia', models.IntegerField(verbose_name='Experiencia')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidad_medico', to='mediApp.especialidad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidad_paciente', to='mediApp.entidad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_medico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=350, verbose_name='Pregunta')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_pregunta', to='mediApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=350, verbose_name='Respuesta')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_respuesta', to='mediApp.medico')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_respuesta', to='mediApp.pregunta')),
            ],
        ),
    ]
